apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/cp4i-es-es-instance.yaml
  - base/cp4i-mq-cluster-ibm-mq-uniform-cluster-instance.yaml
  - instances/cp4i-apic-ibm-cp4i-apic-instance.yaml
