apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cp4i-mq-cluster-ibm-mq-uniform-cluster-instance
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cp4i-mq-cluster
    server: https://kubernetes.default.svc
  project: 2-services
  source:
    path: >-
      payload/2-services/namespace/cp4i-mq-cluster/ibm-mq-uniform-cluster-instance
    repoURL: https://github.com/jabbott7335/cr-cp4i
    targetRevision: main
    helm:
      releaseName: ibm-mq-uniform-cluster-instance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
