apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: cp4i-mq-cluster
spec:
  encryptedData:
    .dockerconfigjson: AgCtW1387+6/upJTyFUIyTNAf4DknUy2hhw260U4YBZjoDJX/wZPlMpGVZbKinZipaXHo1R9tu9ECj1jyNjf+EH43rTm5EfkJlWF0cWh6nNAM59nN3aTsFTC/34vGCUckYTLjp4Y9PzPaJyCF8ZZdXn7+uTtOsUKiYRf/krLytt5IXWLBkrr58HYF+Rk3X/37eVWYexsJC06FLNVUBPf5o+/GBeLXEjbOGAAM4fJ80R4FFCUVL+pQZsLB+HiP/qBSFhpaItbCnWzrLnppdJQMGWPUITQKfERHHzVhKNIfYndR1qLHrNtERqRHraNs0yJOLr7NkCbi48v9gf7Lbzso1j6zE1f3kMe6KGnMmqI4i4gAQ96pjV3yKfVNy+9GnwqQ8hTNIviNyINRgZHKdWtCf16l4wz7nwdXEiyGVVrU0KQ9zfBNFCejD9pgvP6/jY5x7CbJJAawETZsjXFMO4Y/GBzZ673H01d2tHBClWTE8clNgkjklhWk3Zo1+MfIPNr6+6c5Acf+J/KCZwXPCP1I6c1ton2YjuNRypGGSLzBG2iy7t7obZN8F80ZnUmHGFNWWO/rmmbA80Nwk9Z+dqmtTWnWFIp9v9TGnkX7Fdz4pQB8li7F8ytgOb6JikPaQDRlBahsMdxU5wAqa0o3W1UqzAV/H8bu7ZYsGheRtPJyqrDkktYoAUBweIp01eYKmKqsq5HqzRvqRxzrFoGcvs3TmpaEhJoeDafCHpH6dzLQ1mqhE/LfVaZVb2ThPezTDr7pkVxrDboqbRQ4b1kGLUJfAlyL77KatufbILBL5tz8RmbCsGcMf2Vh3J2cccWXHRuXayQVYhTTo5xgGbtxr7Ptj0eJTXovfvZfHh7WZRD5eVMCKr+9h3pV+EyaJvA3FPTZ/FzZvso/DwsxciJq9+EAZo6rXAvzJihB83tA2AuAshpkXzLjEjIoQDEh7MPY2Vrfhb1uq9+OFQCn2iyqFKhnuYbaV9ukUBlvLeTekqII7pmSH0dnJTMRijh9rBhS71tPgbQLZmL50yA8xFmXZDqmU1XoTu1fUm4MKbgjkntWPIsCVBglvmeijfmfjnATnDE9+Bx6okhIr897WY0yLJ4c82RorqgRIij72cIt0Lojhd+oxDtrAfRRUl0FdgpJMBvnV1kjgbszsWSm3ttbxD0KqR/wtKe6wvjWHYf6uQhpUKQNhuICZf1zpeDdSONbj9EOALa+b0k9ztOBo0QSDyPvFvGAXnVDLohxu8ATEExrnDfZACLQT/V3i5FXv9uhJ1mLjuscjkt9IvycDhadCVU3h3dKYcWShXT9GkKfDaJYvnJ4dIASI3NWEJNwMY7B++vXvpM
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: cp4i-mq-cluster
    type: kubernetes.io/dockerconfigjson

