apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: openshift-marketplace
spec:
  encryptedData:
    .dockerconfigjson: AgAV5wrkBUTHE2ZTAIOmF8ncq2AeNkK/ll54J4UvC13eF7ryxQK4CXrNXjfziEMIBBmEAHT6dJZQZ0X2138R3I/WvczPExtMFGcyGHCohRl/kqTRtMALL3xl61uZg78Qq4AwAnIrOKIlEP4DCkWnQxRjR/wg1Hy+/yXruTb8RAsbfWZ7PDFdeHmUH1G7PeaOcGqqEXH41lZamAdp6XJ8mCseQWVz7zaqS6/oDz0hDNslUZHFXtMJorjsViDYrCnXxNlPmLIjX1a6dAhrt1ONXglzNboc7z5xOS/JEdvmrEvGX0qihyirgiMDKzCAt3xJdK6zZSLobLxVQBU+r53rGlu3xk/9Dh01OE0eznSf3E6mopIFyjXFMy+f3JuXwCpkfIN5cXCT9cOLu/PbHd1v8YG7GyFJGMJ7bWOXksIwIldt7/1vVK2RTwjugJQmBlZt24fvRGePMPcBO22gbfNTkFuXsDhxkdzCDsS04+5TVOLMqe71CLo4EYz+zaoqiuOytZkK1XeDrMsnY6lqFbGuX4Sxcv0n1me2dJ/RysbFwrdCni9PdOhwv/EJGozgkIwtuX2h1OHCHwz8YIgi0YoU0wszpERCWr6Th15SkNf2xNVNkxC/5pIea3LOtV5LZqoTQfhmgIbHmrprjq+HDdlhnNAPtu9u1290uLmRNL4pazf23CMy+r/SfHkANNzr/coK+k+xqu4aaRmY91LBtSwK3+8zzKTR1RFh7UaeadlydRNKe8Z9beEMHqitZ6O3p9kx4n85UoCA2TUMnBJTta1VzYHrwfMCifpIdUggx7waQbIx/m2bXFkjY+0cMqO1G/IeX2pbk7Cguhcjsv/TZcilyvnCsQhZnnRbi9PZ3e0RR3orVCW8qUV551H1hRuSHIUjQl9Rkn70F2INUjagLfhX/jJF/QSUuE3n3cmZF9rLE815a6cKloXb40/h0Sn0aotnZWUwPoA4vP3DvZBeidZs25QEqY8yqBjnoI6cO87J+l9Ysbd2q57P3iicmHf9URmPz8RQfjdJuamLUxsGgSfMS7Byrp9mPd1uAf1PT9xQqVc4XK1xe1UDpJNUCHXZYhVTiwpKSJfJdjb0llc/sUd77MhO6OunnJH0TNejL8rn4x2tX6C1gKbYdnQ2cn7NatPbjvEAB3vfFLASgOmkjpcZFbl/c6jiSDb7wY6okHlqJToF38+WZwtnbPNbE/tnkPllYhVFZWahks2eKBilHBni/H1JLaHkq3nN8+PoE9VwrLLi24y43abozQIH5CqKwlDlYC3iLAv9ZOPFlJFGlObxrDk6e70aLPDxvmdaJowEd3TfOBp+aWf7Y91uMxpyLfrUkpUe
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: openshift-marketplace
    type: kubernetes.io/dockerconfigjson

