apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mq_uniform_cluster_instance.configMap.ini.name }}
data:
  config.ini: |-
    AutoCluster:
       {{- range $.Values.mq_uniform_cluster_instance.configMap.ini.AutoCluster }}
       {{ .   }}
       {{- end }}  