apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mq_uniform_cluster_instance.configMap.qm2_mqsc.name }}
data:
  qm2-config.mqsc: |-
    {{- range $.Values.mq_uniform_cluster_instance.configMap.qm2_mqsc.commands }}
    {{ .   }}
    {{- end }}  