apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mq_uniform_cluster_instance.configMap.qm3_mqsc.name }}
data:
  qm3-config.mqsc: |-
    {{- range $.Values.mq_uniform_cluster_instance.configMap.qm3_mqsc.commands }}
    {{ .   }}
    {{- end }}  