"ibm_platform_navigator_operator":
  "name": "ibm-integration-platform-navigator"
  "subscription":
    "channel": "v5.2"
    "installPlanApproval": "Automatic"
    "name": "ibm-integration-platform-navigator"
    "source": "ibm-operator-catalog"
    "sourceNamespace": "openshift-marketplace"

