apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.ibm_apic_operator.subscriptions.ibmapic.name }}
  annotations:
spec:
  {{- toYaml .Values.ibm_apic_operator.subscriptions.ibmapic.subscription | nindent 2 }}
