apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-operators-ibm-ace-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-operators
    server: https://kubernetes.default.svc
  project: 2-services
  source:
    path: payload/2-services/namespace/openshift-operators/ibm-ace-operator
    repoURL: https://github.com/jabbott7335/cr-cp4i
    targetRevision: main
    helm:
      releaseName: ibm-ace-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
