apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-toolkit
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/toolkit/namespace
    repoURL: https://github.com/jabbott7335/cr-cp4i
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
