apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: toolkit-cluster-config
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: toolkit
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/toolkit/cluster-config
    repoURL: https://github.com/jabbott7335/cr-cp4i
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
        - value-default.yaml
      releaseName: cluster-config
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
