apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: toolkit-console-link-job-sa
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: toolkit
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/toolkit/console-link-job-sa
    repoURL: https://github.com/jabbott7335/cr-cp4i
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - jsonPointers:
        - /imagePullSecrets
        - /secrets
      kind: ServiceAccount
